In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('sample.csv')

In [6]:
df

       Name  Country   Age   Salary Purchased
0     James   France  44.0  72000.0        No
1       Tim    Spain  27.0  48000.0       Yes
2     Sarah  Germany  30.0  54000.0        No
3    Robert    Spain  38.0  61000.0        No
4      Emma  Germany  40.0      NaN       Yes
5  Jennifer   France  35.0  58000.0       Yes
6     Linda    Spain   NaN  52000.0        No
7    Thomas   France  48.0  79000.0       Yes
8       Ben  Germany  50.0  83000.0        No
9  Scarlett   France  37.0  67000.0       Yes

## 1. `X`과 `y` 분리
- `X`: machine learning 모델의 입력 (특징, feature)
- `y`: machine learning 모델이 입력을 통해 예측하고자 하는 값 (입력된 특징을 통해 예측해야 하는 목표값, target)

- `X`: Country, Age, Salary 열(column)
- `y`: Purchased 열

### (1) ndarray로 변환 후, Slicing
- `DataFrame`으로부터 columns(열의 이름), index(행의 이름)을 제외한 values만 추출 -> `ndarray`
- ndarray의 slicing으로 X와 y 추출

In [8]:
arr_data = df.values
print(arr_data)
print(type(arr_data))

[['James' 'France' 44.0 72000.0 'No']
 ['Tim' 'Spain' 27.0 48000.0 'Yes']
 ['Sarah' 'Germany' 30.0 54000.0 'No']
 ['Robert' 'Spain' 38.0 61000.0 'No']
 ['Emma' 'Germany' 40.0 nan 'Yes']
 ['Jennifer' 'France' 35.0 58000.0 'Yes']
 ['Linda' 'Spain' nan 52000.0 'No']
 ['Thomas' 'France' 48.0 79000.0 'Yes']
 ['Ben' 'Germany' 50.0 83000.0 'No']
 ['Scarlett' 'France' 37.0 67000.0 'Yes']]
<class 'numpy.ndarray'>

In [9]:
# y: 마지막 열 (전체 행 포함)
yarr = arr_data[:,-1]
print(yarr)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

In [10]:
# X: 첫번째와 마지막열을 제외한 나머지 열 (전체 행 포함)
#    -> 두번째 열(index=1)부터 마지막 열(index=-1) 앞까지 -> 1:-1
Xarr = arr_data[:,1:-1]
print(Xarr)
print(Xarr.shape)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
(10, 3)

### (2) DataFrame으로부터 직접 추출

In [11]:
# y: Purchased 열
y = df['Purchased']
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [13]:
# X: Country, Age, Salary
X = df[['Country','Age','Salary']]
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [15]:
# X: Name과 Purchased를 제외한 나머지 열
X = df.drop(['Name','Purchased'],axis=1)
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

## 2. training data와 test data 분리
- **Training data**: 학습에 사용되는 데이터(X와 y 모두 포함) ex> 학습를 위해 공부하는 예제 문제와 정답
- **Test data**: 학습에 사용되지 않고, 성능 평가를 위해 사용되는 데이터 ex> 실전을 위해 풀어보는 연습 문제와 정답
- **Training data**를 통해서 **machine learning 모델을 생성(학습)** 하고, 해당 모델에 **Test data**의 `X`를 입력한 후, **모델이 예측한 값(prediction)** 과 **Test data**의 `y`(실제 값, target)을 비교하여 성능을 평가한다.

- `train_test_split(X,y,test_size,random_state)`
> - `X, y`: tranining set과 test set으로 분리하고자 하는 `X, y` (하나의 데이터만 입력해도 됨)
> - `test_size`: 전체 데이터에 대한 test set 데이터의 비율 (ex> `test_size=0.2`, trainin data: test data = 8:2)
> - `random_state`: training과 test set으로 분리할 때, 기본적으로 shuffle 한 후, 분리됨. 이 때, 다음 시도에도 동일한 training set과 test set을 얻기 위해서는 radom_state를 특정한 값으로 지정함
> - **반환 순서**: `X_train, X_test, y_train, y_test`

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)
# test_size가 0.3인 경우,
# 전체 10개 데이터 중, training data는 7개, test data는 3개가 됨

In [41]:
print(X_train)
print('----------------------------')
print(X_test)
print('----------------------------')
print(y_train)
print('----------------------------')
print(y_test)
# 전체 10개의 데이터가 지정된 test_size의 비율에 맞춰 training과 test set으로 분리됨
# 이 때, X와 y는 각각 동일한 순서로 shuffle되어 X_train과 y_train, X_test와 y_test의 index가 동일함

   Country   Age   Salary
0   France  44.0  72000.0
7   France  48.0  79000.0
2  Germany  30.0  54000.0
9   France  37.0  67000.0
4  Germany  40.0      NaN
3    Spain  38.0  61000.0
6    Spain   NaN  52000.0
----------------------------
   Country   Age   Salary
8  Germany  50.0  83000.0
1    Spain  27.0  48000.0
5   France  35.0  58000.0
----------------------------
0     No
7    Yes
2     No
9    Yes
4    Yes
3     No
6     No
Name: Purchased, dtype: object
----------------------------
8     No
1    Yes
5    Yes
Name: Purchased, dtype: object

## 3. Encoding
- value가 문자열(str)인 경우, 숫자(numeric value)로 변환이 필요함
- `OrdinalEncoder`: 문자를 정수로 변환
> - ex> 가, 나, 다 -> 0, 1, 2
- `OneHotEncoder`: 문자열을 0과 1로 조합된 벡터로 변환 (하나의 1, 나머지는 0)
> - ex> 가, 나, 다 -> `[1,0,0], [0,1,0], [0,0,1]`
> - 더 자주 사용됨

In [54]:
X = pd.DataFrame({
    'age':[20,30,40],
    'gender':['M','M','F'],
    'city':['Incheon','Busan','Seoul'],
    'income':[3000,5000,7000]
})
X

   age gender     city  income
0   20      M  Incheon    3000
1   30      M    Busan    5000
2   40      F    Seoul    7000

### (1) `OrdinalEncoder`

In [55]:
from sklearn.preprocessing import OrdinalEncoder

In [56]:
enc1 = OrdinalEncoder()

- `OrdinalEncoder.fit(값이 문자열인 DataFrame 또는 ndarray)`: 전달된 값에 따라 어떠한 정수값으로 변환할지 변환식을 생성 (실제 변환 수행 X)
- `OrdinalEncoder.transform(값이 문자열인 DataFrame 또는 ndarray)`: `fit`을 통해 생성된 변환식에 따라 입력된 값을 변환
- `OrdinalEncoder.fit_transform(값이 문자열인 DataFrame 또는 ndarray)`: 변환식 생성과 변환을 한번에 수행
- training data와 test data에 대한 변환식은 반드시 동일해야 하므로, `fit(training_data)`을 수행하여 변환식을 찾았다면, `fit(test_data)`로 변환식 다시 변경해서는 안됨 </br>
`fit(training_data)`로 변환식을 찾은 후, `transform(trainind_data)과 transforma(test_data)`실행함

In [57]:
enc1.fit(X[['gender','city']])
# fit은 반환 결과가 없으며, OrdinalEncoder가 transform할 준비가 됨

OrdinalEncoder()

In [59]:
enc1_X = enc1.transform(X[['gender','city']])
print(enc1_X)
print(type(enc1_X))
# transform의 결과는 ndarray이며, column과 index 정보가 포함되지 않는다.
# 첫번째 어떤 열이고, 어떤 값이 어떤 정수로 변환되었는지 정보는 없다.

[[1. 1.]
 [1. 0.]
 [0. 2.]]
<class 'numpy.ndarray'>

In [79]:
# DataFrame으로 변환한 뒤, 결합
enc2_col = pd.DataFrame(
    enc1_X,
    columns=['gender','city']
)
enc2_col

   gender  city
0     1.0   1.0
1     1.0   0.0
2     0.0   2.0

In [80]:
new_X = pd.concat(
    [X.drop(columns=['gender','city']), enc2_col],
    axis=1
)
new_X

   age  income  gender  city
0   20    3000     1.0   1.0
1   30    5000     1.0   0.0
2   40    7000     0.0   2.0

### (2) OneHotEncoder

In [61]:
from sklearn.preprocessing import OneHotEncoder

In [62]:
enc2 = OneHotEncoder()

In [63]:
enc2.fit(X[['gender','city']])

OneHotEncoder()

In [67]:
enc2_X = enc2.transform(X[['gender','city']])
print(enc2_X)
print(type(enc2_X))
# OneHotEncoder.transform은 변환 결과를 Sparse matrix 형태로 반환함
# Sparse matrix는 메모리를 효율적으로 사용하기 위해, 열의 크기와 몇번째 요소가 1인지의 정보만 가지고 있음
# Sparse matrix는 toarray() method를 통해 ndarray로 변환할 수 있음

  (0, 1)	1.0
  (0, 3)	1.0
  (1, 1)	1.0
  (1, 2)	1.0
  (2, 0)	1.0
  (2, 4)	1.0
<class 'scipy.sparse._csr.csr_matrix'>

In [69]:
enc2_X.toarray()
# 각 열이 무엇을 의미하는지는 알 수 없음

array([[0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.]])

In [71]:
# OneHotEncoder.get_feature_names_out(): 각 열이 무엇을 의미하는지 확인
enc2.get_feature_names_out()
# ex> city_Incheon가 1일 경우: city열의 값인 Incheon

array(['gender_F', 'gender_M', 'city_Busan', 'city_Incheon', 'city_Seoul'],
      dtype=object)

- `OneHotEncoder`의 입력은 DataFrame이었는데, transform의 결과는 Sparse matrix (변환 후, ndarray)
> - DataFrame으로 바꿀 수 없을까?
- `pd.DataFrame(values=ndarray, columns, index)` 활용

In [72]:
enc2_col = pd.DataFrame(
    enc2_X.toarray(), # DataFrame의 values
    columns = enc2.get_feature_names_out()  # DataFrame 열의 이름
    # index는 optional
)
enc2_col

   gender_F  gender_M  city_Busan  city_Incheon  city_Seoul
0       0.0       1.0         0.0           1.0         0.0
1       0.0       1.0         1.0           0.0         0.0
2       1.0       0.0         0.0           0.0         1.0

In [78]:
# X의 나머지 열과 결합
# -> gender와 city가 제외된 X와 gender와 city를 OneHotEncoding한 enc2_col을 결합
new_X = pd.concat(
    [X.drop(['gender','city'],axis=1), enc2_col],
    axis = 1
)
new_X
# 참고로 X.drop(['gender','city'],axis=1)은 X.drop(columns=['gender','city'])와 동일

   age  income  gender_F  gender_M  city_Busan  city_Incheon  city_Seoul
0   20    3000       0.0       1.0         0.0           1.0         0.0
1   30    5000       0.0       1.0         1.0           0.0         0.0
2   40    7000       1.0       0.0         0.0           0.0         1.0